### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by ianwijma** [ianwijma/backrest#1]
Issue
---

The issue that I have with the current name of the project it isn't really unique, and I personally don't find it catchy.

So we are open for suggestions and discussions

**Comment by passabilities** [comment]
Hey there! So I actually started to build my own RESTful API framework using Node to kinda mimic the way Ruby on Rails is set up (minus the frontend or View portion). I have it setup to have a CLI just like Rails so that its easy to spin up a quick project just by typing `backrest init ProjectName`.

If you don't mind, I would really like to use the name `backrest` but I see that you have the name taken on npmjs.com. I wouldn't mind if you wanted to take a look at my project and possibly work on it with me.

**Comment by profesDevelopment** [comment]
@passabilities Is your name 'passabilities' on npmjs? So I can add you as owner and if it succeeded you can remove me for now :) I do LOVE your project idea! But atm my day job is really busy so dont have time yet to contribute to any OSS sadly.

**Comment by passabilities** [comment]
Yes it is and thank you! No problem, I plan on keeping up with this project so it will still be here whenever you want to take a look.

**Comment by profesDevelopment** [comment]
@passabilities I think I have added you are owner now :) So I hope you can change it so you can use it. If you need anything more from me just let me know :)

**Comment by passabilities** [comment]
Awesome, thank you!
